---
# handlers file for ansible-role-tripleo-heat-stack
- name: delete stack
  register: stack_delete_output
  os_stack:
    stack_name: "{{ stack_name }}"
    state: delete
    login_username: "{{ os_username }}"
    login_password: "{{ os_password }}"
    auth_url: "{{ os_auth_url }}"
    tenant_name: "{{ tenant_name }}"

- name: debug heat stack on failure
  register: stack_debug_output
  os_stack:
    stack_name: "{{ stack_name }}"
    state: debug
    login_username: "{{ os_username }}"
    login_password: "{{ os_password }}"
    auth_url: "{{ os_auth_url }}"
    tenant_name: "{{ tenant_name }}"

- name: stack show
  register: stack_debug_output
  os_stack:
    stack_name: "{{ stack_name }}"
    state: show
    login_username: "{{ os_username }}"
    login_password: "{{ os_password }}"
    auth_url: "{{ os_auth_url }}"
    tenant_name: "{{ tenant_name }}"
